import { get } from '@ember/object';
import { first, present, relation, icon, colourTile, fact, relatedFact, money, join, panelOpener, routeOpener, polymorphicType, dateLabel } from './helpers';

/**
 * Places, orders, order configs, service rates, service areas, zones,
 * entities, manifests and recurring order schedules.
 */
export default function buildOperationsDescriptors(owner) {
    return [
        {
            key: 'place',
            labelKey: 'resource.place',
            icon: 'location-dot',
            modelNames: ['place'],
            polymorphicTypes: ['fleet-ops:place', 'Fleetbase\\FleetOps\\Models\\Place'],
            permission: 'fleet-ops view place',
            title: (place) => first(place, 'displayName', 'name', 'address', 'street1', 'public_id'),
            identifier: (place) => join([first(place, 'city'), first(place, 'country')], ', ') ?? first(place, 'public_id'),
            image: () => icon('location-dot'),
            selectDetails: (place) => [first(place, 'address', 'street1'), join([first(place, 'city'), first(place, 'country')], ', ')],
            facts: (place) => [
                fact('address', first(place, 'address', 'street1')),
                fact('phone', first(place, 'phone')),
                fact('type', first(place, 'type'), { format: 'humanize' }),
                relatedFact('vendor', relation(owner, place, 'vendor'), 'vendor', first(place, 'vendor_name')),
                fact('coordinates', first(place, 'positionString') ?? (present(get(place, 'latitude')) ? `${get(place, 'latitude')}, ${get(place, 'longitude')}` : null)),
            ],
            open: panelOpener(owner, 'place-actions'),
        },
        {
            key: 'order',
            labelKey: 'resource.order',
            icon: 'box',
            modelNames: ['order'],
            polymorphicTypes: ['fleet-ops:order', 'Fleetbase\\FleetOps\\Models\\Order'],
            permission: 'fleet-ops view order',
            statusTones: {
                created: 'text-gray-400',
                preparing: 'text-yellow-500',
                dispatched: 'text-yellow-500',
                started: 'text-yellow-500',
                in_progress: 'text-yellow-500',
                enroute: 'text-yellow-500',
                completed: 'text-green-500',
                delivered: 'text-green-500',
                canceled: 'text-red-500',
                cancelled: 'text-red-500',
                failed: 'text-red-500',
            },
            title: (order) => first(order, 'public_id', 'tracking'),
            identifier: (order) => first(order, 'tracking', 'internal_id'),
            image: () => icon('box'),
            status: (order) => first(order, 'status'),
            selectDetails: (order) => [first(order, 'tracking'), first(order, 'status')],
            facts: (order) => [
                fact('status', first(order, 'status'), { format: 'humanize' }),
                relatedFact('customer', relation(owner, order, 'customer'), polymorphicType(order, 'customer', 'customer_type'), first(order, 'customer_name')),
                relatedFact('driver', relation(owner, order, 'driver_assigned'), 'driver', first(order, 'driver_name')),
                fact('route', join([first(order, 'pickupName', 'pickup_name'), first(order, 'dropoffName', 'dropoff_name')], ' → ')),
                fact('scheduled', get(order, 'scheduled_at'), { format: 'date' }),
                fact('order-config', first(order, 'order_config.name', 'type')),
            ],
            open: panelOpener(owner, 'order-actions'),
        },
        {
            key: 'order-config',
            labelKey: 'resource.order-config',
            icon: 'diagram-project',
            modelNames: ['order-config'],
            polymorphicTypes: ['fleet-ops:order-config', 'Fleetbase\\FleetOps\\Models\\OrderConfig'],
            title: (config) => first(config, 'name', 'key', 'public_id'),
            identifier: (config) => first(config, 'key', 'namespace'),
            image: () => icon('diagram-project'),
            status: (config) => first(config, 'status'),
            selectDetails: (config) => [first(config, 'key', 'namespace'), first(config, 'description')],
            facts: (config) => [
                fact('key', first(config, 'key')),
                fact('namespace', first(config, 'namespace')),
                fact('version', get(config, 'version')),
                fact('type', first(config, 'type'), { format: 'humanize' }),
                fact('core-service', typeof get(config, 'core_service') === 'boolean' ? get(config, 'core_service') : null),
                fact('description', first(config, 'description')),
            ],
            open: routeOpener(owner, 'operations.order-config'),
        },
        {
            key: 'service-rate',
            labelKey: 'resource.service-rate',
            icon: 'file-invoice-dollar',
            modelNames: ['service-rate'],
            polymorphicTypes: ['fleet-ops:service-rate', 'Fleetbase\\FleetOps\\Models\\ServiceRate'],
            permission: 'fleet-ops view service-rate',
            title: (rate) => first(rate, 'service_name', 'public_id'),
            identifier: (rate) => first(rate, 'service_type', 'rate_calculation_method'),
            image: () => icon('file-invoice-dollar'),
            selectDetails: (rate) => [first(rate, 'service_type'), first(rate, 'rate_calculation_method')],
            facts: (rate) => [
                fact('calculation', first(rate, 'rate_calculation_method'), { format: 'humanize' }),
                fact('base-fee', money(get(rate, 'base_fee'), get(rate, 'currency'))),
                relatedFact('service-area', relation(owner, rate, 'service_area'), 'service-area', first(rate, 'service_area_name')),
                relatedFact('zone', relation(owner, rate, 'zone'), 'zone', first(rate, 'zone_name')),
                relatedFact('order-config', relation(owner, rate, 'order_config'), 'order-config', first(rate, 'order_config.name')),
                fact('fees', join([get(rate, 'has_cod_fee') ? 'COD' : null, get(rate, 'has_peak_hours_fee') ? 'peak hours' : null], ' · ')),
            ],
            open: panelOpener(owner, 'service-rate-actions'),
        },
        {
            key: 'service-area',
            labelKey: 'resource.service-area',
            icon: 'map',
            modelNames: ['service-area'],
            polymorphicTypes: ['fleet-ops:service-area', 'Fleetbase\\FleetOps\\Models\\ServiceArea'],
            title: (area) => first(area, 'name', 'public_id'),
            identifier: (area) => first(area, 'country', 'type'),
            image: (area) => colourTile(area, 'map'),
            status: (area) => first(area, 'status'),
            selectDetails: (area) => [first(area, 'type'), first(area, 'country')],
            facts: (area) => [
                fact('type', first(area, 'type'), { format: 'humanize' }),
                fact('country', first(area, 'country')),
                fact('zones', relation(owner, area, 'zones')?.length ?? null),
                fact('speed-limit', present(get(area, 'speed_limit_kmh')) ? `${get(area, 'speed_limit_kmh')} km/h` : null),
                fact('triggers', join([get(area, 'trigger_on_entry') ? 'entry' : null, get(area, 'trigger_on_exit') ? 'exit' : null], ' · ')),
            ],
            open: panelOpener(owner, 'service-area-actions'),
        },
        {
            key: 'zone',
            labelKey: 'resource.zone',
            icon: 'draw-polygon',
            modelNames: ['zone'],
            polymorphicTypes: ['fleet-ops:zone', 'Fleetbase\\FleetOps\\Models\\Zone'],
            title: (zone) => first(zone, 'name', 'public_id'),
            identifier: (zone) => first(zone, 'service_area.name', 'service_area_name'),
            image: (zone) => colourTile(zone, 'draw-polygon'),
            status: (zone) => first(zone, 'status'),
            selectDetails: (zone) => [first(zone, 'service_area.name', 'service_area_name'), first(zone, 'description')],
            facts: (zone) => [
                relatedFact('service-area', relation(owner, zone, 'service_area'), 'service-area', first(zone, 'service_area_name')),
                fact('description', first(zone, 'description')),
                fact('speed-limit', present(get(zone, 'speed_limit_kmh')) ? `${get(zone, 'speed_limit_kmh')} km/h` : null),
                fact('dwell', present(get(zone, 'dwell_threshold_minutes')) ? `${get(zone, 'dwell_threshold_minutes')} min` : null),
                fact('triggers', join([get(zone, 'trigger_on_entry') ? 'entry' : null, get(zone, 'trigger_on_exit') ? 'exit' : null], ' · ')),
            ],
            open: panelOpener(owner, 'zone-actions'),
        },
        {
            key: 'entity',
            labelKey: 'resource.entity',
            icon: 'box-open',
            modelNames: ['entity'],
            polymorphicTypes: ['fleet-ops:entity', 'Fleetbase\\FleetOps\\Models\\Entity'],
            title: (entity) => first(entity, 'name', 'sku', 'public_id'),
            identifier: (entity) => first(entity, 'tracking', 'sku'),
            image: (entity) => (present(get(entity, 'photo_url')) ? { url: get(entity, 'photo_url'), shape: 'square' } : icon('box-open')),
            selectDetails: (entity) => [first(entity, 'tracking', 'sku'), first(entity, 'type')],
            facts: (entity) => [
                fact('type', first(entity, 'type'), { format: 'humanize' }),
                fact('dimensions', first(entity, 'dimensions') ?? join([get(entity, 'length'), get(entity, 'width'), get(entity, 'height')], ' × ')),
                fact('weight', first(entity, 'displayWeight') ?? join([get(entity, 'weight'), first(entity, 'weight_unit')])),
                fact('declared-value', money(get(entity, 'declared_value'), get(entity, 'currency'))),
                relatedFact('customer', relation(owner, entity, 'customer'), polymorphicType(entity, 'customer'), first(entity, 'customer.name')),
                relatedFact('destination', relation(owner, entity, 'destination'), 'place', first(entity, 'destination.address')),
            ],
            open: panelOpener(owner, 'entity-actions', { mode: 'modal' }),
        },
        {
            key: 'manifest',
            labelKey: 'resource.manifest',
            icon: 'list-ol',
            modelNames: ['manifest'],
            polymorphicTypes: ['fleet-ops:manifest', 'Fleetbase\\FleetOps\\Models\\Manifest'],
            title: (manifest) => first(manifest, 'public_id', 'internal_id'),
            identifier: (manifest) => first(manifest, 'scheduledDateFormatted', 'scheduled_date'),
            image: () => icon('list-ol'),
            status: (manifest) => first(manifest, 'status'),
            selectDetails: (manifest) => [first(manifest, 'driver_name'), first(manifest, 'status')],
            facts: (manifest) => [
                relatedFact('driver', relation(owner, manifest, 'driver'), 'driver', first(manifest, 'driver_name')),
                relatedFact('vehicle', relation(owner, manifest, 'vehicle'), 'vehicle', first(manifest, 'vehicle_name')),
                fact('status', first(manifest, 'status'), { format: 'humanize' }),
                fact('progress', present(get(manifest, 'stop_count')) ? `${get(manifest, 'completed_stops') ?? 0} of ${get(manifest, 'stop_count')} stops` : null),
                fact('distance', first(manifest, 'totalDistanceKm') ? `${get(manifest, 'totalDistanceKm')} km` : null),
                fact('scheduled', get(manifest, 'scheduled_date'), { format: 'date' }),
            ],
        },
        {
            key: 'recurring-order-schedule',
            labelKey: 'resource.recurring-order-schedule',
            icon: 'repeat',
            modelNames: ['recurring-order-schedule'],
            polymorphicTypes: ['fleet-ops:recurring-order-schedule', 'Fleetbase\\FleetOps\\Models\\RecurringOrderSchedule'],
            statusTones: { active: 'text-green-500', paused: 'text-yellow-500', canceled: 'text-red-500' },
            title: (schedule) => first(schedule, 'name', 'public_id'),
            identifier: (schedule) => dateLabel(get(schedule, 'next_occurrence_at')),
            image: () => icon('repeat'),
            status: (schedule) => first(schedule, 'status'),
            selectDetails: (schedule) => [first(schedule, 'status'), first(schedule, 'timezone')],
            facts: (schedule) => [
                relatedFact('customer', relation(owner, schedule, 'customer'), polymorphicType(schedule, 'customer', 'customer_type'), first(schedule, 'customer.name')),
                relatedFact('driver', relation(owner, schedule, 'driver_assigned'), 'driver', first(schedule, 'driver_assigned.name')),
                relatedFact('vehicle', relation(owner, schedule, 'vehicle_assigned'), 'vehicle', first(schedule, 'vehicle_assigned.displayName')),
                relatedFact('order-config', relation(owner, schedule, 'order_config'), 'order-config', first(schedule, 'order_config.name')),
                fact('next-occurrence', get(schedule, 'next_occurrence_at'), { format: 'date' }),
                fact('timezone', first(schedule, 'timezone')),
            ],
        },
    ];
}
